--Insert Into EntireMissionsDB 
--(Name, Description, State, Parent, DeadLine, CreationDate, RealFinishingDate, Difficulty, Priority)
--Values (N'определеить функционал', N'короче надо написать прогу', 1, 1, '2024-12-21 00:00:00.000', '2023-07-01 00:00:00.000', NULL , 1, 1)
--update EntireMissionsDB set Description = N'понять что хочу от программы' where Id = 2   
--update EntireMissionsDB set State = 0 where State = 1